# This is a basic workflow to help you get started with Actions

name: CI-CD

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  
  workflow_dispatch:


jobs:

  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Autenticando o usuário no Docker
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
          
      - name: Construindo a imagem e enviando para o Docker Hub
        uses: docker/build-push-action@v3.1.1
        with:
           file: ./src/Dockerfile
           context: ./src
           push: true
           tags: |
             israeldoamaral/kube-news:latest
             israeldoamaral/kube-news:${{github.run_number}}
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3

      - name: Definindo o Kube config
        uses: Azure/k8s-set-context@v3.0
        with:     
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}
          
      - name: Efetuando o Deploy no kubernetes
        uses: Azure/k8s-deploy@v4
        with:
          images: israeldoamaral/kube-news:${{github.run_number}}
          manifests: k8s/deployment.yaml
